// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]

use crate::schema::*;
use crate::types::*;
use rocket::serde::json::serde_json;
use diesel::serialize::ToSql;
use diesel::deserialize::FromSql;
use diesel::sql_types::Jsonb;
use diesel::AsExpression;
use serde_json::Value as JsonValue;
use rocket::serde::{ Deserialize, Serialize };

use chrono::NaiveDateTime;
use uuid::Uuid;
use chrono::DateTime;
use chrono::offset::Utc;
use diesel::prelude::*;
#[derive(Clone, Debug, Identifiable, Queryable, QueryableByName, Selectable, Insertable, Serialize, Deserialize, AsChangeset)]
#[diesel(table_name = users)]
pub struct User {
    pub id: Uuid,
    pub name: Option<String>,
    pub profile_picture_url: Option<String>,
    pub email: String,
    pub password: Option<String>,
    pub oauth_provider: String,
    pub oauth_user_id: String,
    pub access_token: String,
    pub refresh_token: Option<String>,
    pub created_at: NaiveDateTime,
    pub updated_at: NaiveDateTime,
    pub last_login: Option<DateTime<Utc>>,
}

